### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by 0xF6** [mastorm/CodeStats.Client#7]

**Comment by Aviortheking** [comment]
The project need to be migrated using this tutorial but I'm not good enough on Visual Studio yet to do it myself

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/migration/update-visual-studio-extension.md

**Comment by AlaiyaNetwork** [comment]
https://github.com/AlaiyaNetwork/CodeStatsForVS

**Comment by 0xF6** [comment]
So, project is dead
